import './global.css'
import ReduxStoreProvider from './ReduxStoreProvider'
export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ReduxStoreProvider>{children}</ReduxStoreProvider>
      </body>
    </html>
  )
}
